openapi: 3.0.0
info:
  title: TrackBite API
  description: API for counting calories and nutrients in food items
  version: 1.0.0

servers:
  - url: http://localhost:3000/

paths:
  /users:
    $ref: './paths/users.yaml'
  /scanned-items:
    $ref: './paths/scannedItems.yaml'
  /recipes:
    $ref: './paths/recipes.yaml'
  /diets:
    $ref: './paths/diets.yaml'
  /daily-intakes:
    $ref: './paths/dailyIntakes.yaml'

components:
    schemas:
      User:
        $ref: './components/user.yaml'
      ScannedItem:
        $ref: './components/scannedItem.yaml'
      DailyIntake:
        $ref: './components/dailyIntake.yaml'
      FoodItem:
        $ref: './components/foodItem.yaml'
      Nutrient:
        $ref: './components/nutrient.yaml'
      Recipe:
        $ref: './components/recipe.yaml'
      Diet:
        $ref: './components/diet.yaml'
      UserCredentials:
        $ref: './components/userCredentials.yaml'
      RecipeRating:
        $ref: './components/recipeRating.yaml'